spring:
  application:
    name: application-consumer
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.186.128:8848
        namespace: d2ca62d0-2fcb-4155-b38e-30f6f908caf1

app:
  id: ${spring.application.name}
apollo:
  cache-dir: 'D:\TeamWork\lcsc-wm-agent-parent\lcsc-wm-springboot-web\src\main\resources\tests'
  autoUpdateInjectedSpringProperties: true
  access-key:
    secret: d7e98dedace8409fca9c956b29cda4b579681f33f54e1ea77ec5589c28419001
  bootstrap:
    enabled: true
    namespaces: application, business, auth.yml,1,2,3,6,5,4,7,8,9,6,5,4,5,9,6,2,15,1,156,5,5
    eagerLoad:
      enabled: true

# logging path
logging:
  config: classpath:logback.xml
  file:
    path: './logs'
